# Generated by Django 5.0.6 on 2024-06-23 08:08

import report.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_imageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='img',
            field=models.ImageField(upload_to=report.models.save_path),
        ),
    ]
