# Generated by Django 5.0.6 on 2024-06-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_imageupload_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportmodel',
            options={'verbose_name': '日報', 'verbose_name_plural': '日報一覧'},
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
