# Generated by Django 5.0.6 on 2024-07-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
