# Generated by Django 5.0.6 on 2024-07-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='public',
            field=models.BooleanField(default=False, verbose_name='公開する'),
        ),
    ]
