# Generated by Django 5.0.6 on 2024-07-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_reportmodel_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
