# Generated by Django 5.0.6 on 2024-07-19 07:21

import report.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_reportmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='slug',
            field=models.SlugField(default=report.models.slug_maker, max_length=20, unique=True),
        ),
    ]
