# Generated by Django 5.0.6 on 2024-07-21 06:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_reportmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
